### PR TITLE
fixing typing as string issue

### PR DESCRIPTION
**Pull request by yibeichan**
Dorota and I tested the converter with `ExtractROI` from `fsl.utils` and found that typing in the input specs was a string, such as `"File"` and `"str"`. 
```
input_fields = [
    (
        "in_file",
        "File",
        {
            "help_string": "input file",
            "argstr": "{in_file}",
            "mandatory": True,
            "position": 0,
        },
    ),
    (
        "roi_file",
        "str",
        {
            "help_string": "output file",
            "argstr": "{roi_file}",
            "position": 1,
            "output_file_template": "{in_file}_trim",
        },
    ),
```

By uncommenting the following in the `write_task()` function, we get the correct typing
``` 
for tp_repl in self.TYPE_REPLACE:
      spec_str = spec_str.replace(*tp_repl)
```
Correct typing `specs.File` and `str` as the following
```
input_fields = [
    (
        "in_file",
        specs.File,
        {
            "help_string": "input file",
            "argstr": "{in_file}",
            "mandatory": True,
            "position": 0,
        },
    ),
    (
        "roi_file",
        str,
        {
            "help_string": "output file",
            "argstr": "{roi_file}",
            "position": 1,
            "output_file_template": "{in_file}_trim",
        },
    ),
```

### CODE REVIEW

**Comment by yibeichan** [comment]
@djarecka ah interesting, I put the ExtractROI into the `example-specs` and found the pytest failed. It might be something related to this function itself. We can discuss about it this Friday.
Also, `ants_registration_Registration` now has `TypeError: '<' not supported between instances of 'type' and 'str'` now. Not sure whether it‘s caused by my uncommenting. @tclose Was this the reason you originally commented out those two lines of code?

**Comment by tclose** [comment]
Yes, I think there was an issue with `'str'` being converted to `str` where it wasn't supposed to be. Could we be more specific with that replacement and only target the datatype lines?

**Comment by yibeichan** [comment]
Hi @tclose sorry for this late reply. @djarecka and I discussed the issue today, and we found out why `ants_registration_Registration` failed the test after I uncommented those two lines.
```
for tp_repl in self.TYPE_REPLACE:
      spec_str = spec_str.replace(*tp_repl)
```
If we comment out those two lines, this [line](https://github.com/nipy/nipype/blob/75796d554394271f1c7cd710b2a1ce8b499989ba/nipype/interfaces/ants/registration.py#L464) from nipype will be converted to 
```
(
        "float",
        "bool",
        {
            "help_string": "Use float instead of double for computations.",
            "argstr": "--float {float}",
        },
    ),
```
If we uncomment those two lines, it will be converted to 
```
(
        float,
        bool,
        {
            "help_string": "Use float instead of double for computations.",
            "argstr": "--float {float}",
        },
    ),
```
now `float` becomes a `type` and will cause errors in this [line](https://github.com/nipype/nipype2pydra/blob/fa9b1491c27c6d547031be5961fb68d1542dd007/tests/test_task.py#L51)

Now I understand what you mean by using regex to specify the replacement.

**Comment by yibeichan** [comment]
@djarecka I found out why the `ExtractROI` test failed.
This [line](https://github.com/nipype/nipype2pydra/blob/fa9b1491c27c6d547031be5961fb68d1542dd007/tests/test_task.py#L51) compares our pydra task specs with nipype specs of `ExtractROI`. So we got 
```
assert ['in_file', 'roi_file', 't_min', 't_size', 'x_min', 'x_size', 'y_min', 'y_size', 'z_min', 'z_size'] == ['crop_list', 'in_file', 'output_type', 'roi_file', 't_min', 't_size', 'x_min', 'x_size', 'y_min', 'y_size', 'z_min', 'z_size']
```
which is like 
```
assert pydra_task.input_spec.fields == nipype_trait_names
```
But `crop_list` and `output_type` are not supposed to appear on the right side (nipype_trait_names). 
So we can add those two to this [list](https://github.com/nipype/nipype2pydra/blob/fa9b1491c27c6d547031be5961fb68d1542dd007/tests/test_task.py#L13), which is used in this [line](https://github.com/nipype/nipype2pydra/blob/fa9b1491c27c6d547031be5961fb68d1542dd007/tests/test_task.py#L55)

I can add it once we think this is the best solution.

**Comment by tclose** [comment]
> Hi @tclose sorry for this late reply. @djarecka and I discussed the issue today, and we found out why `ants_registration_Registration` failed the test after I uncommented those two lines.
> 
> ```
> for tp_repl in self.TYPE_REPLACE:
>       spec_str = spec_str.replace(*tp_repl)
> ```
> 
> If we comment out those two lines, this [line](https://github.com/nipy/nipype/blob/75796d554394271f1c7cd710b2a1ce8b499989ba/nipype/interfaces/ants/registration.py#L464) from nipype will be converted to
> 
> ```
> (
>         "float",
>         "bool",
>         {
>             "help_string": "Use float instead of double for computations.",
>             "argstr": "--float {float}",
>         },
>     ),
> ```
> 
> If we uncomment those two lines, it will be converted to
> 
> ```
> (
>         float,
>         bool,
>         {
>             "help_string": "Use float instead of double for computations.",
>             "argstr": "--float {float}",
>         },
>     ),
> ```
> 
> now `float` becomes a `type` and will cause errors in this [line](https://github.com/nipype/nipype2pydra/blob/fa9b1491c27c6d547031be5961fb68d1542dd007/tests/test_task.py#L51)
> 
> Now I understand what you mean by using regex to specify the replacement.

Yes, that was it. Seeing that example, the regex I suggested still wouldn't work, maybe this one would though


```python

TYPE_REPLACE = [
    (r"(?<=        )'(bool|str)'(?=,\n        {)", r"\1"),
    (r"(?<=        )'(File|Multi.*put.*)'(?=,\n        {)", r"specs.\1"),
]

```

**Comment by yibeichan** [comment]
hi!! I fixed the typing problem with your regex logic, but I wrote something differently (I mean I asked chatgpt to write it).
```
# apply each replacement in TYPE_REPLACE
for old, new in self.TYPE_REPLACE:
    # add a comma and newline to the old string, to match only at the end of lines
    old += ",\n"
    # add a comma and newline to the new string, to replace with
    new += ",\n"
    # use re.sub to replace old with new, in spec_str
    spec_str = re.sub(old, new, spec_str)
```
we still failed the test but only `ExtractROI`, which is a different issue. `ants_registration_Registration` is good now.

**Comment by tclose** [comment]
> hi!! I fixed the typing problem with your regex logic, but I wrote something differently (I mean I asked chatgpt to write it).
> 
> ```
> # apply each replacement in TYPE_REPLACE
> for old, new in self.TYPE_REPLACE:
>     # add a comma and newline to the old string, to match only at the end of lines
>     old += ",\n"
>     # add a comma and newline to the new string, to replace with
>     new += ",\n"
>     # use re.sub to replace old with new, in spec_str
>     spec_str = re.sub(old, new, spec_str)
> ```
> 
> we still failed the test but only `ExtractROI`, which is a different issue. `ants_registration_Registration` is good now.

That's good that it works but I don't get the point of the ChatGPT code, if you want your regex to only match the end of lines you can just use the $ symbol

**Comment by yibeichan** [comment]
> > hi!! I fixed the typing problem with your regex logic, but I wrote something differently (I mean I asked chatgpt to write it).
> > ```
> > # apply each replacement in TYPE_REPLACE
> > for old, new in self.TYPE_REPLACE:
> >     # add a comma and newline to the old string, to match only at the end of lines
> >     old += ",\n"
> >     # add a comma and newline to the new string, to replace with
> >     new += ",\n"
> >     # use re.sub to replace old with new, in spec_str
> >     spec_str = re.sub(old, new, spec_str)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > we still failed the test but only `ExtractROI`, which is a different issue. `ants_registration_Registration` is good now.
> 
> That's good that it works but I don't get the point of the ChatGPT code, if you want your regex to only match the end of lines you can just use the $ symbol

so the code does the replacement only when the strings are followed by a comma and a newline

**Comment by yibeichan** [comment]
> @djarecka I found out why the `ExtractROI` test failed. This [line](https://github.com/nipype/nipype2pydra/blob/fa9b1491c27c6d547031be5961fb68d1542dd007/tests/test_task.py#L51) compares our pydra task specs with nipype specs of `ExtractROI`. So we got
> 
> ```
> assert ['in_file', 'roi_file', 't_min', 't_size', 'x_min', 'x_size', 'y_min', 'y_size', 'z_min', 'z_size'] == ['crop_list', 'in_file', 'output_type', 'roi_file', 't_min', 't_size', 'x_min', 'x_size', 'y_min', 'y_size', 'z_min', 'z_size']
> ```
> 
> which is like
> 
> ```
> assert pydra_task.input_spec.fields == nipype_trait_names
> ```
> 
> But `crop_list` and `output_type` are not supposed to appear on the right side (nipype_trait_names). So we can add those two to this [list](https://github.com/nipype/nipype2pydra/blob/fa9b1491c27c6d547031be5961fb68d1542dd007/tests/test_task.py#L13), which is used in this [line](https://github.com/nipype/nipype2pydra/blob/fa9b1491c27c6d547031be5961fb68d1542dd007/tests/test_task.py#L55)
> 
> I can add it once we think this is the best solution.

I just tested, adding `crop_list` and `output_type` to this [list](https://github.com/nipype/nipype2pydra/blob/fa9b1491c27c6d547031be5961fb68d1542dd007/tests/test_task.py#L13) solved the problem.

Also I removed the test input [here](https://github.com/yibeichan/nipype2pydra/blob/e14d0284c14965c8de7c03fe2d4663d93a719cc5/example-specs/task/fsl_utils_ExtractROI.yaml#L15) because we don't have any test data. 
now all tests are passed.

**Comment by tclose** [comment]
I was thinking that including the following line up until the open brace '{' would differentiate between the two

**Comment by yibeichan** [comment]
> But isn't float followed by comma and a newline in the ANTs registration case
> 
> ```
> (
>         "float",
>         "bool",
>         {
>             "help_string": "Use float instead of double for computations.",
>             "argstr": "--float {float}",
>         },
>     ),
> ```

yes, in this case, we want to convert `"bool"` to `bool` while keeping `"float"` as `"float"`. 
oh, I typed something wrong... I mean the ChatGPT code does the replacement only when a string follows a comma and a new line...
you mean we want to use `xxx, +\n +{` as an identifier instead of `, +\n xxx`

**Comment by tclose** [comment]
>  you mean we want to use `xxx, +\n +{` as an identifier instead of `, +\n xxx`

Yes, this is what I was thinking, maybe explicitly typing out the full indentation so it is guaranteed to be at the top level

**Comment by yibeichan** [comment]
we probably don't want to use `{` because in `ants_registration_Registration` we have something like the following, where `{` is not next to the trait type

```
(
        "use_histogram_matching",
        ty.Any,
        True,
        {"help_string": "Histogram match the images before registration."},
    ),
    (
        "interpolation",
        ty.Any,
        "Linear",
        {"help_string": "", "argstr": "{interpolation}"},
    ),
    ("interpolation_parameters", ty.Any, {"help_string": ""}),
    (
        "write_composite_transform",
        bool,
        False,
        {
            "help_string": "",
            "argstr": "--write-composite-transform {write_composite_transform}",
        },
    ),
```

**Comment by tclose** [comment]
It might be better to target the `attrs.field` style syntax then

**Comment by tclose** [comment]
Or you could do a negative look-behind for 

```
(
        
```

**Comment by yibeichan** [comment]
> It might be better to target the `attrs.field` style syntax then

sorry, not very familiar with this. what do you mean by "target the `attrs.field` style syntax"

a negative look-behind for `(?<!\(\n        )` is easier for me to understand. I can do this one. But I still want to know what the `attrs.field` style syntax is, haha

**Comment by tclose** [comment]
Otherwise written as `attr.ib`, is an optional way to declare the Pydra interface, see the [output specs in the docs as an example](https://pydra.readthedocs.io/en/latest/output_spec.html)

**Comment by yibeichan** [comment]
> Otherwise written as `attr.ib`, is an optional way to declare the Pydra interface, see the [output specs in the docs as an example](https://pydra.readthedocs.io/en/latest/output_spec.html)

ah, make sense. okay, let's choose one. `attr.ib` or `negative look-behind`?

**Comment by tclose** [comment]
I'm thinking a better way to handle this would be to escape the types in a pair of "#", e.g. "#float#", which we can be confident of stripping out after the code is generated, rather than messing around with regexes

**Comment by yibeichan** [comment]
ah! hello!! and sorry for not getting back to this issue earlier. I was
traveling and moving for the past few weeks. I'll work on it the coming
week!!

**Comment by yibeichan** [comment]
hello! (after another week...) okay, your idea inspired me, but I didn't add a pair of `#` for types. Instead, I add a prefix `'TYPE_'` -> `'TYPE_list'`. And it worked! In this case, we don't have to touch regex
okay, this PR requires a reviewer, but I can't assign anyone to review... I guess you will review it? then this problem solved?

**Review by tclose — APPROVED** [review]
Nice idea with the "TYPE_" prefix it is much more explicit. All looks good to me :)

**Pull request merged**
